/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.*;

/**
 *
 * @author victorprens
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    private ArrayList diagramaFlujo = new ArrayList();
    ArrayList<Variable> Variables = new ArrayList();
    ArrayList<Imprimir> Imprimir = new ArrayList();
    ArrayList<Asignacion> Asignacion = new ArrayList();
    ArrayList<Operacion> Operacion = new ArrayList();
    private int posicion = 1;
    private Archivo file = new Archivo();
    Diagrama l;
    Conector c=null;
    Decision d=null;
    Entradasalida es=null;
    Proceso p=null;
    Terminal t=null;
    int xanterior=0;
    int yanterior=0;
    int indexobjeto = 0;
    boolean arrastrando;
    boolean tamaño;
    Object objeto;
    
    public Principal() {
        initComponents();
        setSize(1024, 700);
        setLocationRelativeTo(null);
        l = new Diagrama();
        l.setBounds(0, 0,jPanel1.getWidth() , jPanel1.getHeight());
        l.setBackground(Color.white);
        jPanel1.add(l);
        
    }
    


    public int getPosicion() {
        return posicion;
    }

    public void setPosicion(int posicion) {
        this.posicion = posicion;
    }

    public ArrayList getDiagramaFlujo() {
        return diagramaFlujo;
    }

    public void setDiagramaFlujo(ArrayList diagramaFlujo) {
        this.diagramaFlujo = diagramaFlujo;
    }

    public Archivo getFile() {
        return file;
    }

    public void setFile(Archivo file) {
        this.file = file;
    }

    public ArrayList<Variable> getVariables() {
        return Variables;
    }

    public void setVariables(ArrayList<Variable> Variables) {
        this.Variables = Variables;
    }

    public ArrayList<Imprimir> getImprimir() {
        return Imprimir;
    }

    public void setImprimir(ArrayList<Imprimir> Imprimir) {
        this.Imprimir = Imprimir;
    }

    public ArrayList<Asignacion> getAsignacion() {
        return Asignacion;
    }

    public void setAsignacion(ArrayList<Asignacion> Asignacion) {
        this.Asignacion = Asignacion;
    }

    public ArrayList<Operacion> getOperacion() {
        return Operacion;
    }

    public void setOperacion(ArrayList<Operacion> Operacion) {
        this.Operacion = Operacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaHerramientas = new javax.swing.JPanel();
        botonProceso = new javax.swing.JButton();
        botonDecision = new javax.swing.JButton();
        botonTerminal = new javax.swing.JButton();
        botonES = new javax.swing.JButton();
        botonConector = new javax.swing.JButton();
        botonLinea = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campocadena = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        camponombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campotipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(78, 78, 78));
        setForeground(new java.awt.Color(113, 113, 113));

        botonProceso.setText("Proceso");
        botonProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProcesoActionPerformed(evt);
            }
        });

        botonDecision.setText("Decision");
        botonDecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDecisionActionPerformed(evt);
            }
        });

        botonTerminal.setText("Terminal");
        botonTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminalActionPerformed(evt);
            }
        });

        botonES.setText("E/S");
        botonES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonESActionPerformed(evt);
            }
        });

        botonConector.setText("Conector");
        botonConector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConectorActionPerformed(evt);
            }
        });

        botonLinea.setText("Linea");
        botonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLineaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cajaHerramientasLayout = new javax.swing.GroupLayout(cajaHerramientas);
        cajaHerramientas.setLayout(cajaHerramientasLayout);
        cajaHerramientasLayout.setHorizontalGroup(
            cajaHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaHerramientasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cajaHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonTerminal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonDecision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonConector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        cajaHerramientasLayout.setVerticalGroup(
            cajaHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaHerramientasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(botonProceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonDecision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonTerminal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonConector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonLinea)
                .addContainerGap(463, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 889, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel1.setText("CADENA");

        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel3.setText("TIPO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(campocadena)
            .addComponent(camponombre)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(campotipo)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campocadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camponombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cajaHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProcesoActionPerformed
        this.setEnabled(false);
        VentanaOperacion vo = new VentanaOperacion();
        vo.setVisible(true);
        vo.setP(this);        
    }//GEN-LAST:event_botonProcesoActionPerformed

    private void botonDecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDecisionActionPerformed
        //iniciarFigura("decision");
    }//GEN-LAST:event_botonDecisionActionPerformed

    private void botonTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminalActionPerformed
        iniciarFigura("terminal", "inicio");
    }//GEN-LAST:event_botonTerminalActionPerformed

    private void botonESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonESActionPerformed
        this.setEnabled(false);
        VentanaVariables vv = new VentanaVariables();
        vv.setVisible(true);
        vv.setP(this);  
        //iniciarFigura("es");
    }//GEN-LAST:event_botonESActionPerformed

    private void botonConectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConectorActionPerformed
        //iniciarFigura("conector");
    }//GEN-LAST:event_botonConectorActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
    boolean bandera = false;    
    boolean bandera2 = false;
    int x = evt.getX();
    int y = evt.getY();
    String nombreclase = "";

        if (!arrastrando) {
            nulificador();
                for (int i = 0; i < l.getObjetos().size(); i++) {
                nombreclase = l.getObjetos().get(i).getClass().getName();
                convierteObjeto(nombreclase, l.getObjetos().get(i));
                bandera = dentrodelArea(x, y);
                bandera2 = dentrodelBorde(x, y);
                    if (bandera || bandera2) {
                        objeto = l.getObjetos().get(i);
                        break;
                    } else {
                        nulificador();
                    }
            }
        }
        if (bandera2) {
            eventoAgrandar(x, y);
        }
        else{
            eventoMover(x, y);    
        }
            
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        int x = evt.getX();
        int y = evt.getY();
        String nombreclase = "";
        boolean bandera = false;    
            nulificador();
                for (int i = 0; i < l.getObjetos().size(); i++) {
                    nombreclase = l.getObjetos().get(i).getClass().getName();
                    convierteObjeto(nombreclase, l.getObjetos().get(i));
                    bandera = dentrodelArea(x, y);
                    if (bandera){
                        objeto = l.getObjetos().get(i);
                        break;
                    }
                    else{
                        nulificador();
                    }
                }
            
                if (bandera) {
                    finalizador3();
                }
                
                            
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
       arrastrando = false;
       setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanel1MouseMoved

    private void botonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLineaActionPerformed
        //iniciarFigura("linea");
    }//GEN-LAST:event_botonLineaActionPerformed
    
    private void convierteObjeto(String nombre,Object o){
        switch (nombre) {
            case "vista.Conector":
                c = (Conector) o;
                break;
                
            case "vista.Decision":
                d = (Decision) o;
                break;
                
            case "vista.Entradasalida":
                es = (Entradasalida) o;
                break;
                
            case "vista.Proceso":
                p = (Proceso) o;
                break;
                
            case "vista.Terminal":
                t = (Terminal) o;
                break;    
            default:
                throw new AssertionError();
        }
        
    }
    
    private boolean dentrodelArea(int x, int y){
        boolean b = false;    
            if(c!=null){
                if(x>c.x && x<c.x + c.ancho && y>c.y && y<c.y + c.alto){
                    arrastrando(x,y);
                    b = true;
                }
            } 
            else if(d!=null){
                if(x>d.vx[0] && x<d.vx[2] && y>d.vy[3] && y<d.vy[1] ){
                    arrastrando(x,y);
                    b = true;
                }
            }
            else if(es!=null){
                if(x>es.vx[0] && x<es.vx[2] && y>es.vy[1] && y<es.vy[0]){
                    arrastrando(x,y);
                    b = true;
                }
            }
            else if(p!=null){
                if(x>=p.x && x<=p.x + p.ancho && y>=p.y && y<=p.y + p.alto){
                    arrastrando(x,y);
                    b = true;
                }
            }
            else if(t!=null){
                if(x>=t.x && x<=t.x + t.ancho && y>=t.y && y<=t.y + t.alto){
                    arrastrando(x,y);
                    b = true;
                }
            }
        return b;
    }
    
    private boolean dentrodelBorde(int x, int y){
        boolean b = false;    
            if(c!=null){
                if(x>c.borde.x && x<c.borde.x + c.borde.grosor && y>c.borde.y && y<c.borde.y + c.borde.alto //lado izquiero
                   || x>c.borde.x && x<c.borde.x + c.borde.ancho && y>c.borde.y && y<c.borde.y + c.borde.grosor // lado arriba
                   || x>c.borde.x + c.borde.ancho - c.borde.grosor && x<c.borde.x + c.borde.ancho&& y>c.borde.y && y<c.borde.y + c.borde.alto // lado derecho
                   || x>c.borde.x && x<c.borde.x + c.borde.ancho && y>c.borde.y +c.borde.alto -c.borde.grosor && y<c.borde.y + c.borde.alto// lado abajo            
                   ){
                    arrastrando(x,y);
                    b = true;
                    setCursor(new Cursor(Cursor.W_RESIZE_CURSOR));
                }
            } 
            else if(d!=null){
                if(x>d.vx[0] && x<d.vx[2] && y>d.vy[3] && y<d.vy[1] ){
                    arrastrando(x,y);
                    b = true;
                }
            }
            else if(es!=null){
                if(x>es.vx[0] && x<es.vx[2] && y>es.vy[1] && y<es.vy[0]){
                    arrastrando(x,y);
                    b = true;
                }
            }
            else if(p!=null){
                if(x>=p.x && x<=p.x + p.ancho && y>=p.y && y<=p.y + p.alto){
                    arrastrando(x,y);
                    b = true;
                }
            }
            else if(t!=null){
                if(x>=t.x && x<=t.x + t.ancho && y>=t.y && y<=t.y + t.alto){
                    arrastrando(x,y);
                    b = true;
                }
            }
        return b;
    }
    
    private void eventoMover(int x,int y){
        
            if (c!= null) {
                c.x= c.x + (x - xanterior);
                c.y= c.y + (y - yanterior);
                xanterior = x;
                yanterior = y;
                finalizador("conector");
            }                
            else if(d!=null){
                
                for (int i = 0; i < 4; i++) {
                    d.vx[i]= d.vx[i] + (x - xanterior);
                    d.vy[i]= d.vy[i] + (y - yanterior);
                }
                xanterior = x;
                yanterior = y;
                finalizador("decision");
            }
            else if(es!=null){
                
                for (int i = 0; i < 4; i++) {
                    es.vx[i]= es.vx[i] + (x - xanterior);
                    es.vy[i]= es.vy[i] + (y - yanterior);
                }
                
                xanterior = x;
                yanterior = y;
                finalizador("es");
            }
            else if(p!=null){
                p.x= p.x + (x - xanterior);
                p.y= p.y + (y - yanterior);
                xanterior = x;
                yanterior = y;
                finalizador("proceso");
            }
            else if(t!=null){
                t.x= t.x + (x - xanterior);
                t.y= t.y + (y - yanterior);
                xanterior = x;
                yanterior = y;
                finalizador("terminal");
            }
            
    }
    
    private void eventoAgrandar(int x, int y){
             if (c!= null) {
                c.ancho= c.ancho + (x - xanterior);
                c.alto= c.alto + (y - yanterior);
                 System.out.println(c.ancho);
                 System.out.println(c.alto);
                xanterior = x;
                yanterior = y;
                finalizador4("conector");
            }                
            else if(d!=null){
                
                for (int i = 0; i < 4; i++) {
                    d.vx[i]= d.vx[i] + (x - xanterior);
                    d.vy[i]= d.vy[i] + (y - yanterior);
                }
                xanterior = x;
                yanterior = y;
                finalizador4("decision");
            }
            else if(es!=null){
                
                for (int i = 0; i < 4; i++) {
                    es.vx[i]= es.vx[i] + (x - xanterior);
                    es.vy[i]= es.vy[i] + (y - yanterior);
                }
                
                xanterior = x;
                yanterior = y;
                finalizador4("es");
            }
            else if(p!=null){
                p.x= p.x + (x - xanterior);
                p.y= p.y + (y - yanterior);
                xanterior = x;
                yanterior = y;
                finalizador4("proceso");
            }
            else if(t!=null){
                t.x= t.x + (x - xanterior);
                t.y= t.y + (y - yanterior);
                xanterior = x;
                yanterior = y;
                finalizador4("terminal");
            }
            
    }
    
    private void obtenerDatos(){
            if(c!=null){
                campocadena.setText(c.cadena);
                camponombre.setText(c.nombre);
                campotipo.setText("conector");
            } 
            else if(d!=null){
                campocadena.setText(d.cadena);
                camponombre.setText(d.nombre);
                campotipo.setText("decision");
            }
            else if(es!=null){
                campocadena.setText(es.cadena);
                camponombre.setText(es.nombre);
                campotipo.setText("entradasalida");
            }
            else if(p!=null){
                campocadena.setText(p.cadena);
                camponombre.setText(p.nombre);
                campotipo.setText("proceso");
            }
            else if(t!=null){
                campocadena.setText(t.cadena);
                camponombre.setText(t.nombre);
                campotipo.setText("terminal");
            }
    }
    
    public void cambiandoTamaño(int x, int y){
        xanterior = x;
        yanterior = y;
        tamaño = true;
    }
    public void arrastrando(int x, int y){
        xanterior = x;
        yanterior = y;
        arrastrando = true;
    }
    
    public void nulificador(){
        p = null;
        c = null;
        d = null;
        es = null;
        t = null;
    }
    
    public void iniciarFigura(String cadena, String nombre){
        
        String expresion = JOptionPane.showInputDialog("Ingrese la cadena para el componente.");
        finalizador2(cadena, nombre, expresion);
    }
    
    public void finalizador(String cadena){
        l.setTipo(cadena);
        l.setObjeto(objeto);
        l.setAccion("mover");
//        l.setPosicion(indexobjeto);
        l.repaint();
    }
    
    public void finalizador2(String cadena, String nombre, String expresion){
        l.setTipo(cadena);
        l.setAccion("crear");
        l.setExpresion(expresion);
        l.setNombre(nombre);
        l.repaint();
        
    }
    
    public void finalizador3(){
        l.setAccion("borde");
        l.setObjeto(objeto);
        l.repaint();
        obtenerDatos();                                                      
    }
    
    private void finalizador4(String cadena) {
        l.setTipo(cadena);
        l.setAccion("tamaño");
        l.setPosicion(indexobjeto);
        l.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConector;
    private javax.swing.JButton botonDecision;
    private javax.swing.JButton botonES;
    private javax.swing.JButton botonLinea;
    private javax.swing.JButton botonProceso;
    private javax.swing.JButton botonTerminal;
    private javax.swing.JPanel cajaHerramientas;
    private javax.swing.JTextField campocadena;
    private javax.swing.JTextField camponombre;
    private javax.swing.JTextField campotipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
