/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.Expresiones;
import logica.Variable;
import logica.Variables;

/**
 *
 * @author Estudiante
 */
public class VentanaVariables extends javax.swing.JFrame {

    private Principal p;
    private ArrayList<Variable> var = new ArrayList<>();
    private Variables v;

    /**
     * Creates new form VentanaVariables
     */
    public VentanaVariables() {
        initComponents();
    }

    public Principal getP() {
        return p;
    }

    public void setP(Principal p) {
        this.p = p;
    }

    public ArrayList<Variable> getVar() {
        return var;
    }

    public void setVar(ArrayList<Variable> var) {
        this.var = var;
    }

    public Variables getV() {
        return v;
    }

    public void setV(Variables v) {
        this.v = v;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtVariable1 = new javax.swing.JTextField();
        txtVariable2 = new javax.swing.JTextField();
        txtVariable3 = new javax.swing.JTextField();
        cbxTipo1 = new javax.swing.JComboBox();
        cbxTipo2 = new javax.swing.JComboBox();
        cbxTipo3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("variables:");

        cbxTipo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Int", "String", "Double", "Float", "Boolean" }));

        cbxTipo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Int", "String", "Double", "Float", "Boolean" }));

        cbxTipo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Int", "String", "Double", "Float", "Boolean" }));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("CREACION DE VARIABLES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtVariable1)
                            .addComponent(txtVariable2)
                            .addComponent(txtVariable3, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxTipo1, 0, 76, Short.MAX_VALUE)
                            .addComponent(cbxTipo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxTipo3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVariable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVariable2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVariable3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTipo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Expresiones e = new Expresiones();
        if (txtVariable1.getText().equals("") && txtVariable2.getText().equals("") && txtVariable3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite una variable");
        } else {
            //verifica con una expresion si es la cadena valida o no
            //Si no estan vacios los campos entonces agrega la variable
            if (!e.verificarCadena(txtVariable1.getText()) || !e.verificarCadena(txtVariable1.getText()) || !e.verificarCadena(txtVariable1.getText())) {
                //esto es para que no se repitan las variables que ponga pero no quiere salir
                if(!txtVariable1.getText().equals(txtVariable2.getText()) && !txtVariable1.getText().equals(txtVariable3.getText()) && !txtVariable2.getText().equals(txtVariable3.getText())){
                if (!"".equals(txtVariable1.getText())) {
                    //crea una variable y la guarda en el arraylist de variables asi con las tres
                    Variable v1 = new Variable(txtVariable1.getText(), cbxTipo1.getSelectedItem().toString());
                    var.add(v1);
                    getP().getFile().getVariables().add(v1);
                    System.out.println("creó " + v1.getVariable());
                }

                if (!"".equals(txtVariable2.getText())) {

                    Variable v2 = new Variable(txtVariable2.getText(), cbxTipo2.getSelectedItem().toString());
                    var.add(v2);
                    getP().getFile().getVariables().add(v2);
                    System.out.println("creó " + v2.getVariable());
                }

                if (!"".equals(txtVariable3.getText())) {
                    if (!e.verificarCadena(txtVariable1.getText())) {
                        Variable v3 = new Variable(txtVariable3.getText(), cbxTipo3.getSelectedItem().toString());
                        var.add(v3);
                        getP().getFile().getVariables().add(v3);
                        System.out.println("creó " + v3.getVariable());
                    }
                }
                
                getP().getFile().getVariables().add(var);
                v = new Variables(var);
                v.setPosicion(getP().getPosicion());
                getP().setPosicion(getP().getPosicion() + 1);
                String vars = " ";
                //AQUI LE MANDO EL TEXTO QUE VA A APARECER EN EL GRAFICO
                for (int i = 0; i < var.size(); i++) {
                    vars+=var.get(i).getVariable() + " : " + var.get(i).getTipo()+" \n";
                }
                getP().iniciarFigura("es", vars);
                this.dispose();
                getP().setVisible(true);
                getP().setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(null, "Variables repetidas");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Digite una cadena correcta");
            }

        }
        getP().getDiagramaFlujo().add(var);//agrega la figura creada al ArrayList diagrama de flujo
        getP().setVariables(var);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.getP().setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.getP().setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVariables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVariables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVariables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVariables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVariables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxTipo1;
    private javax.swing.JComboBox cbxTipo2;
    private javax.swing.JComboBox cbxTipo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtVariable1;
    private javax.swing.JTextField txtVariable2;
    private javax.swing.JTextField txtVariable3;
    // End of variables declaration//GEN-END:variables
}
